defaults: &defaults
  login_ticket:
    lifetime: 600
  service_ticket:
    lifetime_unconsumed: 300
    lifetime_consumed: 86400
  proxy_ticket:
    lifetime_unconsumed: 300
    lifetime_consumed: 86400

development:
  <<: *defaults
  authenticators:
    static:
      class: "CASino::Authenticators::Static"
      options:
        users:
          testuser:
            password: "foobar123"

test:
  <<: *defaults
  authenticators:
    static:
      class: "CASino::Authenticators::Static"
      options:
        users:
          testuser:
            password: "foobar123"
