#!/usr/bin/env rake
# Add your own tasks in files placed in lib/tasks ending in .rake,
# for example lib/tasks/capistrano.rake, and they will automatically be available to Rake.

require File.expand_path('../config/application', __FILE__)

Dummy::Application.load_tasks

task :environment do
  verbosity = ActiveRecord::Schema.verbose
  ActiveRecord::Schema.verbose = false
  schema = File.join(Rails.root, 'db','schema.rb')
  if File.exists? schema
    load schema
  else
    puts "#{schema} not found. Skipping schema load"
  end
  ActiveRecord::Schema.verbose = verbosity
end